apiVersion: v1
kind: Namespace
metadata:
  name: petclinic
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: px-repl3-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: petclinic
  annotations:
    volume.beta.kubernetes.io/storage-class: px-repl3-sc
  name: petclinic-db-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: petclinic
  creationTimestamp: null
  labels:
    app: petclinic-db-mysql
  name: petclinic-db-mysql
  selfLink: /api/v1/namespaces/default/services/petclinic-db-mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: petclinic-db-mysql
  sessionAffinity: None
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30333
  selector:
    app: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      schedulerName: stork
      containers:
      - name: petclinic
        image: springdeveloper/spring-petclinic:2.0.0.BUILD-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'production,kubernetes'
        - name: MYSQL_HOST
          value: petclinic-db-mysql
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: supermysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: petclinic
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: petclinic-db-mysql
  name: petclinic-db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-db-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-db-mysql
    spec:
      schedulerName: stork
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: supermysql
        - name: MYSQL_PASSWORD
          value: supermysql
        - name: MYSQL_USER
        - name: MYSQL_DATABASE
          value: petclinic
        image: mysql:5.7.33
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: petclinic-db-mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - rm
        - -fr
        - /var/lib/mysql/lost+found
        image: busybox:1.29.3
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: petclinic-db-mysql
