{
 "title": "Autopilot",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Actions state",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(sum(increase(autopilot_action_failed_count{state=\"declined\"}[$__range]))) > 0",
     "legendFormat": "declined"
    },
    {
     "expr": "floor(sum(increase(autopilot_action_failed_count{state=\"failed\"}[$__range]))) > 0",
     "legendFormat": "failed"
    },
    {
     "expr": "sum by (job) (increase(autopilot_action_taken_total[$__range]))",
     "legendFormat": "succeed"
    }
   ]
  },
  {
   "title": "Declined actions detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (object) (floor(increase(autopilot_action_failed_total{object=~\".*\",state=\"declined\"}[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Failed actions details",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum by (object) (floor(increase(autopilot_action_failed_total{object=~\".*\",state=\"failed\"}[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Rules in the system",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "autopilot_rules_in_system" }
   ]
  },
  {
   "title": "Actions taken per rule in time period (total)",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum by (rule_name) (increase(autopilot_action_taken_total[$__range]))"
    }
   ]
  },
  {
   "title": "Objects being monitored",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "autopilot_objects_with_rules_total"
    }
   ]
  }
 ]
}
{
 "title": "Portworx Cluster Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  {
   "title": "Portworx Cluster \"[[Cluster]]\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Usage Meter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\"})/sum(px_cluster_disk_total_bytes{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Avg. Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(px_cluster_cpu_percent{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "# Nodes (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"[[Cluster]]\"})/sum(px_cluster_status_cluster_quorum{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "# Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_nodes_online{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=\"[[Cluster]]\"})-min(px_cluster_status_storage_nodes_online{cluster=\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "CPU utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster =~ \"[[Cluster]]\"}"
    }
   ]
  },
  {
   "title": "Memory utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_memory_utilized_percent{cluster =~ \"[[Cluster]]\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "Portworx Node Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" },
   { "name": "Instances", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"[[Cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "PWX Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_disk_total_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Instances \"[[Instances]]\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage: $tag_cluster - $tag_node",
     "expr": "px_cluster_cpu_percent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_cpu_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Usage: $tag_node",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_memory_utilized_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Memory Usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "IO Bytes TX",
     "expr": "px_network_io_bytessent{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes TX",
     "measurement": "px_network_io_bytessent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Bytes RX",
     "expr": "px_network_io_received_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes RX",
     "measurement": "px_network_io_received_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX  Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_read_seconds {cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Read {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_write_seconds {cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Write  {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "irate(px_disk_stats_read_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "irate(px_disk_stats_write_bytes{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_disk_stats_read_latency_seconds{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_disk_stats_write_latency_seconds{cluster=~\"[[Cluster]]\",instance=~\"[[Instances]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Portworx Volume Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "px_cluster_cpu_percent" },
   {
    "name": "Volumes",
    "label": "Volume Name",
    "query": "px_volume_depth_io {cluster=\"[[Cluster]]\"}"
   }
  ]
 },
 "panels": [
  { "title": "All Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Read Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Top n Volumes by Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (10,(px_volume_usage_bytes{cluster=~\"[[Cluster]]\"}/px_volume_capacity_bytes{cluster=~\"[[Cluster]]\"})*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top n Volumes by IO depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,px_volume_depth_io{cluster=\"[[Cluster]]\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Avg Write Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  { "title": "Volume: [[Volumes]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "Volumes" },
  {
   "title": "Current Replication Level (HA)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_currhalevel{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Priority",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_iopriority{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
    }
   ]
  },
  {
   "title": "Avg Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Capacity",
     "expr": "px_volume_capacity_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " Capacity",
     "measurement": "px_volume_capacity_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Disk Usage",
     "expr": "px_volume_usage_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " Usage",
     "measurement": "px_volume_usage_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Replication Level (HA)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "px_volume_halevel{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{volumename}}",
     "measurement": "px_volume_halevel",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume total reads/writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_num_long_reads{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of  Reads ",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_num_long_writes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "No. of  Writes ",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_iops{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "IOPs",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Read/Written Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_read_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read ",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_written_bytes{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written ",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Read Latency",
     "expr": "px_volume_vol_read_latency_seconds{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Read Latency",
     "measurement": "px_volume_vol_read_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Write Latency",
     "expr": "px_volume_vol_write_latency_seconds{volumename=~\"[[Volumes]]\"}\n",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "Write Latency",
     "measurement": "px_volume_vol_write_latency_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IO Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "px_volume_depth_io{volumename=~\"[[Volumes]]\"}",
     "legendFormat": "I/O Depth"
    }
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes Written Throughput",
     "expr": "px_volume_readthroughput{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Read Throughput",
     "measurement": "px_volume_writethroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Bytes Read Throughput",
     "expr": "px_volume_writethroughput{volumename=~\"[[Volumes]]\"}",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes Written Throughput",
     "measurement": "px_volume_readthroughput",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
      { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Etcd Dashboard",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}} Resident Memory" }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  }
 ]
}