apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-image
  namespace: pxbbq
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    cdi.kubevirt.io/storage.usePopulator: "false"
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/minimal/releases/noble/release/ubuntu-24.04-minimal-cloudimg-amd64.img"
  pvc:
    storageClassName: px-rwx-kubevirt
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi~                         