#!/bin/bash

#
# creates a deployment on PDS and a spring-petclinic instance accessing it
# 
# will also create a /px-deploy/script-delete/pds-petclinic.sh script to remove everything being created by this script
# this will be used by px-deploy to delete PDS Deployments/Targets prior to deleting the px-deploy instance
#
# currently tested only on terraform based aws ec2/ocp4/eks instances 
# 
# TODO: React on disabled Versions (14.4)
#
# when running standalone ensure the following variables are set properly
# and  /assets/pds-petclinic/pds-petclinic.tpl exists & is accessible
#
# PDS_TOKEN="[your pds user api key]"
# name="pds-demo"
# cluster=1
# platform="ocp4"
# PDS_ENDPOINT="https://prod.pds.portworx.com/api"
# PDS_NAMESPACE="pds-petclinic"
# PDS_DATASERVICE="pg"
# PDS_DATASERVICE_VERSION="13.11"
# PDS_APP_CONFIG_TEMPLATE="Default"
# PDS_APP_RESOURCE_TEMPLATE="Tiny"
# PDS_APP_STORAGE_TEMPLATE="Volume%20replication%20(best-effort%20spread)"
# PDS_ACCOUNT="Sales"
# PDS_TENANT="Default"
# PDS_PROJECT="Default"
#

kubectl create ns $PDS_NAMESPACE
kubectl label ns $PDS_NAMESPACE pds.portworx.com/available=true

TGT_NAME="px-deploy-$name-$cluster"

[[ -z $PDS_TOKEN ]] && { echo "env variable PDS_TOKEN not set. check your ~/.px-deploy/defaults.yml"; exit 1; }

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/accounts?Name=$PDS_ACCOUNT"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_ACCOUNT_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_ACCOUNT_ID == "null" ]] && { echo "PDS_ACCOUNT_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_ACCOUNT_ID=\"$PDS_ACCOUNT_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/accounts/$PDS_ACCOUNT_ID/tenants?Name=$PDS_TENANT"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_TENANT_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_TENANT_ID == "null" ]] && { echo "PDS_TENANT_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_TENANT_ID=\"$PDS_TENANT_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/projects?Name=$PDS_PROJECT"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_PROJECT_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_PROJECT_ID == "null" ]] && { echo "PDS_PROJECT_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_PROJECT_ID=\"$PDS_PROJECT_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/service-accounts?Name=Default-AgentWriter"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_SERVICE_ACCOUNT_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_SERVICE_ACCOUNT_ID == "null" ]] && { echo "PDS_SERVICE_ACCOUNT_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_SERVICE_ACCOUNT_ID=\"$PDS_SERVICE_ACCOUNT_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/service-accounts/$PDS_SERVICE_ACCOUNT_ID/token"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_SERVICE_ACCOUNT_TOKEN=$(echo $OUTPUT | jq -r '.token')
[[ $PDS_SERVICE_ACCOUNT_TOKEN == "null" ]] && { echo "PDS_SERVICE_ACCOUNT_TOKEN not found"; echo $OUTPUT; exit 1; }
echo "PDS_SERVICE_ACCOUNT_TOKEN=\"$PDS_SERVICE_ACCOUNT_TOKEN\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/data-services?short_name=$PDS_DATASERVICE"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_DATASERVICE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_DATASERVICE_ID == "null" ]] && { echo "PDS_DATASERVICE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_DATASERVICE_ID=\"$PDS_DATASERVICE_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/data-services/$PDS_DATASERVICE_ID/versions?name=$PDS_DATASERVICE_VERSION&enabled=true"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_DATASERVICE_VERSION_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_DATASERVICE_VERSION_ID == "null" ]] && { echo "PDS_DATASERVICE_VERSION_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_DATASERVICE_VERSION_ID=\"$PDS_DATASERVICE_VERSION_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/images?data_service_id=$PDS_DATASERVICE_ID&version_id=$PDS_DATASERVICE_VERSION_ID&latest=true"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_DATASERVICE_IMAGE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_DATASERVICE_IMAGE_ID == "null" ]] && { echo "PDS_DATASERVICE_IMAGE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_DATASERVICE_IMAGE_ID=\"$PDS_DATASERVICE_IMAGE_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/application-configuration-templates?name=$PDS_APP_CONFIG_TEMPLATE&data_service_id=$PDS_DATASERVICE_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_APP_CONFIG_TEMPLATE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_APP_CONFIG_TEMPLATE_ID == "null" ]] && { echo "PDS_APP_CONFIG_TEMPLATE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_APP_CONFIG_TEMPLATE_ID=\"$PDS_APP_CONFIG_TEMPLATE_ID\""

OUTPUT=$(curl -s -X "GET"  "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/resource-settings-templates?name=$PDS_APP_RESOURCE_TEMPLATE&data_service_id=$PDS_DATASERVICE_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_APP_RESOURCE_TEMPLATE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_APP_RESOURCE_TEMPLATE_ID == "null" ]] && { echo "PDS_APP_RESOURCE_TEMPLATE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_APP_RESOURCE_TEMPLATE_ID=\"$PDS_APP_RESOURCE_TEMPLATE_ID\""

OUTPUT=$(curl -s -X "GET"  "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/storage-options-templates?name=$PDS_APP_STORAGE_TEMPLATE&provisioner=auto"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_APP_STORAGE_TEMPLATE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_APP_STORAGE_TEMPLATE_ID == "null" ]] && { echo "PDS_APP_STORAGE_TEMPLATE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_APP_STORAGE_TEMPLATE_ID=\"$PDS_APP_STORAGE_TEMPLATE_ID\""

OUTPUT=$(curl -s -X "GET" "$PDS_ENDPOINT/metadata" -H 'Accept: application/json' -H "Authorization: Bearer $PDS_TOKEN")
PDS_HELM_CHART_VERSION=$(echo $OUTPUT | jq -r '.helm_chart_version')
[[ $PDS_HELM_CHART_VERSION == "null" ]] && { echo "PDS_HELM_CHART_VERSION not found"; echo $OUTPUT; exit 1; }
echo "PDS_HELM_CHART_VERSION=\"$PDS_HELM_CHART_VERSION\""

if [ "$platform" = ocp4 ]; then
	PDSPLATFORM="--set platform=ocp"
else
	PDSPLATFORM=""
fi

helm install --create-namespace --namespace=pds-system pds pds-target --repo=https://portworx.github.io/pds-charts --version=$PDS_HELM_CHART_VERSION $PDSPLATFORM --set tenantId=$PDS_TENANT_ID --set bearerToken=$PDS_SERVICE_ACCOUNT_TOKEN --set apiEndpoint=$PDS_ENDPOINT

echo "Waiting for pds-agent to get ready"
kubectl wait pods -n pds-system -l app=pds-agent  --for condition=Ready --timeout -1s

PDS_DEPLOYMENT_TARGET_NAME=$(kubectl get ns kube-system -o json |jq -r ".metadata.uid")
echo "PDS_DEPLOYMENT_TARGET_NAME=\"$PDS_DEPLOYMENT_TARGET_NAME\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/tenants/$PDS_TENANT_ID/deployment-targets?cluster_id=$PDS_DEPLOYMENT_TARGET_NAME"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_DEPLOYMENT_TARGET_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_DEPLOYMENT_TARGET_ID == "null" ]] && { echo "PDS_DEPLOYMENT_TARGET_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_DEPLOYMENT_TARGET_ID=\"$PDS_DEPLOYMENT_TARGET_ID\""

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID/namespaces?name=$PDS_NAMESPACE"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_NAMESPACE_ID=$(echo $OUTPUT | jq -r '.data[0].id')
[[ $PDS_NAMESPACE_ID == "null" ]] && { echo "PDS_NAMESPACE_ID not found"; echo $OUTPUT; exit 1; }
echo "PDS_NAMESPACE_ID=\"$PDS_NAMESPACE_ID\""

echo "Renaming Deployment Target from kube-system uuid to $TGT_NAME"
curl -s -X "PUT" "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID" -H "accept: application/json" -H "Authorization: Bearer $PDS_TOKEN" -H "Content-Type: application/json" -d "{ \"name\": \"$TGT_NAME\"}" > /dev/null

echo "Creating Deployment"

OUTPUT=$(curl -s -X "POST" "$PDS_ENDPOINT/projects/$PDS_PROJECT_ID/deployments" -H "accept: application/json" -H "Authorization: Bearer $PDS_TOKEN" -H "Content-Type: application/json" -d '{ 
"node_count":1, 
"name":"'$TGT_NAME'", 
"data_service_id":"'$PDS_DATASERVICE_ID'", 
"project_id":"'$PDS_PROJECT_ID'", 
"tenant_id":"'$PDS_TENANT_ID'", 
"account_id":"'$PDS_ACCOUNT_ID'", 
"deployment_target_id":"'$PDS_DEPLOYMENT_TARGET_ID'", 
"namespace_id":"'$PDS_NAMESPACE_ID'", 
"service_type":"NodePort",
"dns_zone":"pds-petclinic.svc.cluster.local",
"image_id":"'$PDS_DATASERVICE_IMAGE_ID'",
"application_configuration_template_id":"'$PDS_APP_CONFIG_TEMPLATE_ID'",
"resource_settings_template_id":"'$PDS_APP_RESOURCE_TEMPLATE_ID'",
"storage_options_template_id":"'$PDS_APP_STORAGE_TEMPLATE_ID'"
}')

PDS_DEPLOYMENT_ID=$(echo $OUTPUT  | jq -r '.id' )
[[ $PDS_DEPLOYMENT_ID == "null" ]] && { echo "Deployment failed."; echo $OUTPUT; exit 1; }
echo "PDS_DEPLOYMENT_ID=\"$PDS_DEPLOYMENT_ID\""

PDS_DEPLOYMENT_STATUS=""

while [ "$PDS_DEPLOYMENT_STATUS" != "Available" ]; do
	sleep 5
	PDS_DEPLOYMENT_STATUS=$(curl -s -X "GET"   "$PDS_ENDPOINT/deployments/$PDS_DEPLOYMENT_ID/status"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')
	echo "Current Depl Status:	$PDS_DEPLOYMENT_STATUS		$(date)"
done

OUTPUT=$(curl -s -X "GET"   "$PDS_ENDPOINT/deployments/$PDS_DEPLOYMENT_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")
PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME=$(echo $OUTPUT | jq -r '.cluster_resource_name')
[[ $PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME == "null" ]] && { echo "PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME not found"; echo $OUTPUT; exit 1; }
echo "PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME=\"$PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME\""


PDS_CONNECTION=$(curl -s -X "GET"   "$PDS_ENDPOINT/deployments/$PDS_DEPLOYMENT_ID/connection-info"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN")

PDS_VIP=$(echo $PDS_CONNECTION | jq -r '.clusterDetails.host')

PDS_PORT=$(echo $PDS_CONNECTION | jq -r '.clusterDetails.port')

# create a deletion script which will be run by px-deploy before destroying instance
echo "Creating deletion script /px-deploy/script-delete/pds-petclinic.sh"

cat <<EOF > /px-deploy/script-delete/pds-petclinic.sh
#!/bin/bash
echo "Deleting PDS-Petclinic Deployment"
curl -X "DELETE"   "$PDS_ENDPOINT/deployments/$PDS_DEPLOYMENT_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN" 

echo "Deleting Namespace $PDS_NAMESPACE"
kubectl delete namespace $PDS_NAMESPACE --wait=false

echo "Deleting pds helm deployment"

helm delete pds -n pds-system

echo "Deleting pds-system namespace"

kubectl delete namespace pds-system --wait=false

DEPLOY_STAT=\$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')

[[ \$DEPLOY_STAT == "null" ]] && { echo "Deployment Status empty. ";  exit 1; }

echo "Waiting for Deployment Target to become unhealthy (this can take up to 5min)"

while [ "\$DEPLOY_STAT" != "unhealthy" ]; do
	sleep 5
	echo "Current State	\$DEPLOY_STAT	\$(date)"
	DEPLOY_STAT=\$(curl -s -X "GET"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"  | jq -r '.status')

done

echo "Deleting Deployment Target"

curl -s -X "DELETE"   "$PDS_ENDPOINT/deployment-targets/$PDS_DEPLOYMENT_TARGET_ID"   -H "accept: application/json"   -H "Authorization: Bearer $PDS_TOKEN"

EOF

echo "PDS Deployment Ready"
echo "Creating Petclinic Application"

sed -e "s/(NAMESPACE)/$PDS_NAMESPACE/g" -e "s/(VIP)/$PDS_VIP/g" -e "s/(PORT)/$PDS_PORT/g" -e "s/(CREDS)/$PDS_DEPLOYMENT_CLUSTER_RESOURCE_NAME-creds/g" /assets/pds-petclinic/pds-petclinic.tpl > /assets/pds-petclinic/pds-petclinic.yaml

kubectl apply -f /assets/pds-petclinic/pds-petclinic.yaml

